[package]
name = "pace26stride"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
ctrlc = "3.5.1"
env_logger = { version="0.11.8", default-features = false, features = ["auto-color"] }
log = "0.4.28"
num_cpus = "1.17.0"
pace26io = { git = "https://github.com/manpen/pace26io.git" }
pace26checker = { git = "https://github.com/manpen/pace26checker.git" }
serde = { version = "1.0.228", features = ["derive"] }
structopt = "0.3.26"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "process", "time", "fs"] }
derive_builder = "0.20.2"
libc = "0.2.177"
tracing = "0.1.41"
serde_json = "1.0.145"
glob = "0.3.3"

[dev-dependencies]
tempdir = "0.3.7"

[[bin]]
name = "stride"

[[bin]]
name = "test_solver"